### ISSUE TITLE
Option for dark theme and option to start with folder non-expanded

### ISSUE THREAD

**Issue by rasssta** [DirkHeinke/ha-automations-tree-panel#1]
As I have a dark theme it's hard to read the automation names. It would be nice to have an option for light / dark theme. See example below.

<img width="198" alt="image" src="https://user-images.githubusercontent.com/4455235/213887506-61a32b2e-9a6a-4001-a793-c7908f920d4c.png">

Also, I'd prefer to start off with all folder in a "closed" / non-expanded state when I open the page. An option for this would be nice.

Thanks!

**Comment by DirkHeinke** [comment]
With the improved code from @VibroAxe the colors are now fixed and you can set `defaultOpenTreeDepth=1;` or `0`.
