### ISSUE TITLE
Start in collapsed view

### ISSUE THREAD

**Issue by frank-dusign** [DirkHeinke/ha-automations-tree-panel#11]
I have a lot of automation, so in the current startup view (expanded) it needs a lot of scrolling.
Is it possible to a have a item collapsed at start / reload of page.

**Comment by Firewolf1337** [comment]
The description of how to do that is in the [customization](https://github.com/DirkHeinke/ha-automations-tree-panel#customization) section.

**Comment by DirkHeinke** [comment]
Hello @frank-dusign. As said, you can set the `defaultOpenTreeDepth` to `0`. Then all tree elements should be closed. If you have any problems with it, let me know.

**Comment by frank-dusign** [comment]
Thanks, did saw that.
