### ISSUE TITLE
Adding a column "enabled/disabled" in the automations table

### ISSUE THREAD

**Issue by brasofilo** [DirkHeinke/ha-automations-tree-panel#3]
Hi, thanks a lot for this useful tool!

In each automation we have the `automation-name` and `automation-last-run` columns.
I'd like to add an enabled/disabled column.

My first try to modify the `renderAutomation()` method was unsuccessful as my first `console.log` did not even work, lol
How should I go about it?
Thanks again!

**Comment by DirkHeinke** [comment]
Hi, thanks for the idea. 

I altered your idea a bit: Disabled automations are now strikethrough.
![image](https://user-images.githubusercontent.com/5230945/220758151-cbee1ee7-a37a-4298-8385-57853c53ecd9.png)

I hope that solves your request.

**Comment by brasofilo** [comment]
Most excellent, your solution is perfect, easy visual indicator. 
Thanks!!
