### ISSUE TITLE
Persistent configuration

### ISSUE THREAD

**Issue by wsw70** [DirkHeinke/ha-automations-tree-panel#5]
Today, when updating `ha-automations-tree-panel` the existing configuration will get overwritten.

Is there a way to have them persist? I would be happy to do a PR for that but since I have never written anything for HA I do not know where to start (I found nothing in the documentation)

**Comment by DirkHeinke** [comment]
I think it should work to add a config section to the panel: https://developers.home-assistant.io/docs/frontend/custom-ui/creating-custom-panels/#introduction
As this is my first HA project as well, we have to experiment 😄

**Comment by DirkHeinke** [comment]
This should be fixed with the latest release. I would love to get feedback if it works for you.
