### ISSUE TITLE
Sorting automations

### ISSUE THREAD

**Issue by richardcastle** [DirkHeinke/ha-automations-tree-panel#8]
What a great tool! Thank you for your contribution to the community.

I noticed that the automations tree didn't seem to sort the automations alphabetically. Is that something that could be added?

I'm no expert in .js, however I did try to experiment with adding the line:

automations.sort((a,b) => a.friendly_name - b.friendly_name);

To the getAutomations() method, however I couldn't get it to work. Perhaps someone can suggest how to achieve this?

Richard

**Comment by DirkHeinke** [comment]
Hi,

I tested your idea and it seems to work.

Add this code:
```
    tree.children.sort((a,b) => {
     return a.name.localeCompare(b.name)
    });
    tree.automations.sort((a,b) => {
      return a.path[0].localeCompare(b.path[0])
    });
```
here:
![image](https://github.com/DirkHeinke/ha-automations-tree-panel/assets/5230945/8eb11588-3533-4d35-b9f3-d996d533e303)


I'll add this to the code if you can confirm that it works.

**Comment by richardcastle** [comment]
Yes! It works perfectly. Thank you so much for the recommended change!

Out of interest, there seems to be a whole load of issues with caching and difficulties in HA to recognise that the .js file has been updated. Any tips and tricks here? For most of my browsers I've got to force a cache clear to get it to work. It has yet to change on the HA app on my Android....
